import About from "@/components/About";
import CarouselIndex from "@/components/Carousel";
import FAQs from "@/components/FAQs";
import Landing from "@/components/Landing";
import Prizes from "@/components/Prizes/Prizes";
<<<<<<< HEAD
import Sponsors from "@/components/Sponsors";
import Timeline from "@/components/Timeline";
import { Metadata } from "next";
=======
import Team from "@/components/Team";
>>>>>>> 4738d6f468bcf647b6fad652ad36b30a5a8bde8d

export default function Home() {
  return (
<<<<<<< HEAD
    <main id="main" className="w-full relative flex overflow-x-hidden flex-col items-center">
=======
    <div className="-z-10 font-AtypDisplay background-bg flex flex-col">
>>>>>>> 4738d6f468bcf647b6fad652ad36b30a5a8bde8d
      <Landing />
      <About />
      <CarouselIndex />
      <Prizes />
      <Timeline />
      <Sponsors />
      <FAQs />
    </main>
  );
<<<<<<< HEAD
}


export const metadata: Metadata = {
  title: "Hack2Future",
  description: "Generated by create next app",
};
=======
}
>>>>>>> 4738d6f468bcf647b6fad652ad36b30a5a8bde8d
