import About from '@/components/About';
import CarouselIndex from '@/components/Carousel';
import FAQs from '@/components/FAQs';
import Landing from '@/components/Landing';
import Prizes from '@/components/Prizes/Prizes';
import ProblemStatements from '@/components/ProblemStatements/Index';
import Sponsors from '@/components/Sponsors';
import Timeline from '@/components/Timeline';
import { Metadata } from 'next';

export default function Home() {
  return (
    <main
      id="main"
      className="relative flex w-full flex-col items-center overflow-x-hidden"
    >
      <Landing />
      <About />
      {/* <CarouselIndex/> */}
      <ProblemStatements />
      <Prizes />
      <Timeline />
      <Sponsors />
      <FAQs />
    </main>
  );
}

export const metadata: Metadata = {
  title: 'Hack2Future',
  description: 'Generated by create next app',
};
